#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup
import urllib.parse
import sys

headers = {
     "User-Agent": "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:141.0) Gecko/20100101 Firefox/141.0",
     "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
     "Accept-Language": "en-US,en;q=0.5",
     "Accept-Encoding": "gzip, deflate, br, zstd",
     "Referer": "https://html.duckduckgo.com/",
     "Origin": "https://html.duckduckgo.com"
}

def web_search(query):

    url = f"https://html.duckduckgo.com/html/" 
    data = {
            'q': query,
            'kl': 'us-en'
            }

    response = requests.post(url, headers=headers, data=data)

    if 'anomaly' in response.text:
        print("DDG thinks we're a bot!")
        return None

    soup = BeautifulSoup(response.text, 'html.parser')
    results= soup.find_all(class_='result__a') 
    first = None
    for i in results:
        if "www.cpubenchmark.net/cpu.php" in i.attrs['href']:
            first = i.attrs['href']
            break
    firstlink = first if first else None

    return firstlink


def fetch_result(url):
    color_code = '#F48A18'
    response = requests.get(url, headers=headers)
    html_content = response.text

    #<title>403 Forbidden</title>
    if "403 Forbidden" in html_content:
        print("Error - can't get passmark rating\n",url, html_content)
        sys.exit(1)

    soup = BeautifulSoup(html_content, 'html.parser')

    ratings = []
    for div in soup.find_all('div', style=True):
        style = div.get('style', '')
        if color_code in style:
            ratings.append(div.get_text(strip=True))

    name = soup.find('div', class_='productheader')
    name = name.get_text(strip=True)

    data = [] 
    dats = soup.find_all('div', class_='left-desc-cpu')
    for d in dats:
        for ele in d.find_all('p'):
            data.append(ele)

    dats = soup.find_all('div', class_='desc-foot')
    for d in dats:
        for ele in d.find_all('p'):
            data.append(ele)

    dats = soup.find_all('div', class_='desc-body')
    for d in dats:
        for ele in d.find_all('p'):
            data.append(ele)

    socket = None
    power = None
    cores = None
    pPERp = None

    for line in data:
        #print(line)
        if 'Socket:' in line.text and not socket:
            socket = line.contents[1].strip()
        if 'TDP:' in line.text and not power:
            power = line.contents[1].strip()
        if 'Cores' in line.text and not cores:
            cores = line.text
        if 'CPUmark/$Price:' in line.text and not pPERp:
            pPERp = line.text

    if not socket:
        socket = "unknown"
    if not power:
        power = "unknown"
    if not cores:
        cores = "unknown"
    if not pPERp:
        pPERp = "unknown"

    return name, ratings, cores, socket, power, pPERp

def main():
    query = "cpubenchmark " + " ".join(sys.argv[1:])

    link = web_search(query)
    if not link:
        print("No link found")
        sys.exit()
    elif "cpubenchmark.net" not in link:
        print("No valid result found")
        sys.exit()

    vals = fetch_result(link)
    print(vals)



if __name__ == "__main__":
    main()
