#!/usr/bin/env python3

import requests
from bs4 import BeautifulSoup
import urllib.parse
import sys

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate",
    "Connection": "keep-alive",
    "Upgrade-Insecure-Requests": "1",

    # Chrome “fetch metadata” headers
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same-origin",
    "Sec-Fetch-User": "?1",
}

def direct_search(args):
    """ expects query to be a bunch of terms concatenated together with +
        returns the likely looking link to the item """

    #urlorig = f"https://www.passmark.com/search/zoomsearch.php?zoom_sort=0&zoom_xml=0&zoom_per_page=10&zoom_and=1&zoom_cat%5B%5D=-1&zoom_query=i5+1245U"
    query = "+".join(args)
    url = f"https://www.passmark.com/search/zoomsearch.php"
    data = {
            "zoom_query": query,
            "zoom_sort": 0,
            "zoom_xml": 0,
            "zoom_per_page": 10,
            "zoom_and": 1,
            "zoom_cat[]": 5, #cat 5 is "benchmark results" theoretically
            }

    response = requests.get(url, headers=headers, params=data)

    soup = BeautifulSoup(response.text, "html.parser")
    filtered_links = []

    for div in soup.find_all("div", class_="result_title"):
        a = div.find("a", href=True)
        if not a:
            continue

        href = a["href"]
        qs = urllib.parse.parse_qs(urllib.parse.urlparse(href).query)

        # keep only URLs that have id=...
        if "id" not in qs:
            continue

        # omit any URL that has cpuCount=...
        if "cpuCount" in qs:
            continue

        filtered_links.append(href)

    return filtered_links

def fetch_result(url):
    color_code = '#F48A18'
    response = requests.get(url, headers=headers)
    html_content = response.text

    #cloudflare blocking
    if "cloudflare" in html_content.lower():
        print("Error - looks like cloudflare doesn't like our user agent - blocked\n", url, html_content)
        sys.exit(1)

    #<title>403 Forbidden</title>
    if "403 Forbidden" in html_content:
        print("Error - can't get passmark rating\n",url, html_content)
        sys.exit(1)

    soup = BeautifulSoup(html_content, 'html.parser')

    ratings = []
    for div in soup.find_all('div', style=True):
        style = div.get('style', '')
        if color_code in style:
            ratings.append(div.get_text(strip=True))

    name = soup.find('div', class_='productheader')
    name = name.get_text(strip=True)

    data = [] 
    dats = soup.find_all('div', class_='left-desc-cpu')
    for d in dats:
        for ele in d.find_all('p'):
            data.append(ele)

    dats = soup.find_all('div', class_='desc-foot')
    for d in dats:
        for ele in d.find_all('p'):
            data.append(ele)

    dats = soup.find_all('div', class_='desc-body')
    for d in dats:
        for ele in d.find_all('p'):
            data.append(ele)

    socket = None
    power = None
    cores = None
    pPERp = None

    for line in data:
        #print(line)
        if 'Socket:' in line.text and not socket:
            socket = line.contents[1].strip()
        if 'TDP:' in line.text and not power:
            power = line.contents[1].strip()
        if 'Cores' in line.text and not cores:
            cores = line.text
        if 'CPUmark/$Price:' in line.text and not pPERp:
            pPERp = line.text

    if not socket:
        socket = "unknown"
    if not power:
        power = "unknown"
    if not cores:
        cores = "unknown"
    if not pPERp:
        pPERp = "unknown"

    return name, ratings, cores, socket, power, pPERp

def main():

    links = direct_search(sys.argv[1:])
    if len(links) == 0 :
        print("No link found")
        sys.exit()
    gotresult = 0;
    for link in links:
        #print(link)
        #print("----")
        if "cpubenchmark.net" in link:
            gotresult = 1
            print(fetch_result(link))
            continue
        if not gotresult:
            print("No valid result found")




if __name__ == "__main__":
    main()
